# Generated by Django 5.2 on 2026-09-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('Hombre', 'Moda Hombre'), ('Mujer', 'Moda Mujer'), ('Niños', 'Moda Infantil / Niños'), ('Unisex', 'Línea Unisex')], max_length=20)),
                ('categoria', models.CharField(choices=[('Polos', 'Polos y Camisas'), ('Jeans', 'Pantalones y Jeans'), ('Casacas y Poleras', 'Casacas y Poleras'), ('Vestidos', 'Vestidos y Faldas'), ('Ropa Deportiva', 'Ropa Deportiva'), ('Calzado', 'Calzado')], max_length=40)),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('4-6', '4-6 años'), ('8-10', '8-10 años'), ('12-14', '12-14 años'), ('Única', 'Talla Única')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
