# Generated by Django 5.2 on 2026-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo en el sistema o archivado'),
        ),
    ]
